[
    {
      "title": "Mandarin Chinese",
      "wikiLink": "https://en.wikipedia.org/wiki/Mandarin_Chinese",
      "imageUrl": "images/mandarin chinese.png",
      "altText": "Example of Chinese characters",
      "text": "Mandarin Chinese is the most widely spoken language in the world with over a billion speakers. It is the official language of mainland China and Taiwan, and one of the official languages in Singapore. Mandarin is a tonal language with four distinct tones that can change the meaning of a word.",
      "totalSpeakers": "1.12 billion",
      "languageFamily": "Sino-Tibetan",
      "sampleGreeting": "你好 (Nǐ hǎo)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Zh-n%C7%90h%C7%8Eo.ogg"
    },
    {
      "title": "Spanish",
      "wikiLink": "https://en.wikipedia.org/wiki/Spanish_language",
      "imageUrl": "images/spanish.jpg",
      "altText": "Spanish language text example",
      "text": "Spanish is a Romance language with approximately 480 million native speakers, making it the second most spoken language by number of native speakers. It is the official language in 20 countries, primarily in Spain and Latin America, and is widely spoken as a second language across the globe.",
      "totalSpeakers": "534 million",
      "languageFamily": "Indo-European, Romance",
      "sampleGreeting": "¡Hola! ¿Cómo estás?",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Es-us-hola.ogg"
    },
    {
      "title": "English",
      "wikiLink": "https://en.wikipedia.org/wiki/English_language",
      "imageUrl": "images/english.png",
      "altText": "Page from William Blake's 'The Tyger' showing English text",
      "text": "English is a West Germanic language that originated from Anglo-Frisian dialects brought to Britain in the mid 5th to 7th centuries AD. With around 400 million native speakers, it has become the world's lingua franca, with an estimated 1.35 billion total speakers. It is the official language in 59 countries and is widely used in business, science, and international communication.",
      "totalSpeakers": "1.35 billion",
      "languageFamily": "Indo-European, Germanic",
      "sampleGreeting": "Hello! How are you?",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e0/En-us-hello.ogg"
    },
    {
      "title": "Hindi",
      "wikiLink": "https://en.wikipedia.org/wiki/Hindi",
      "imageUrl": "images/hindi.png",
      "altText": "Example of Hindi script",
      "text": "Hindi is an Indo-Aryan language spoken primarily in India. It is the fourth most spoken first language in the world with approximately 341 million native speakers. Written in the Devanagari script, Hindi is one of the 22 scheduled languages of India and is the official language of the Indian government alongside English.",
      "totalSpeakers": "600 million",
      "languageFamily": "Indo-European, Indo-Aryan",
      "sampleGreeting": "नमस्ते (Namaste)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Hi-Namaste.ogg"
    },
    {
      "title": "Arabic",
      "wikiLink": "https://en.wikipedia.org/wiki/Arabic",
      "imageUrl": "images/arabic.png",
      "altText": "Arabic calligraphy from Wazir Khan Mosque",
      "text": "Arabic is a Semitic language that originated on the Arabian Peninsula. It is the liturgical language of Islam and the official language of 26 states, though its many varieties can be quite different from each other. Modern Standard Arabic serves as the standardized, literary form used in formal contexts across the Arab world.",
      "totalSpeakers": "420 million",
      "languageFamily": "Afro-Asiatic, Semitic",
      "sampleGreeting": "السلام عليكم (As-salamu alaykum)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Ar-Assalaamu_aleikum.ogg"
    },
    {
      "title": "Bengali",
      "wikiLink": "https://en.wikipedia.org/wiki/Bengali_language",
      "imageUrl": "images/bengali.png",
      "altText": "Example of Bengali script",
      "text": "Bengali, also known as Bangla, is an Indo-Aryan language primarily spoken in Bangladesh and in the Indian states of West Bengal, Tripura, and parts of Assam. With approximately 230 million native speakers, it is the fifth most spoken native language in the world. The Bengali script is derived from the Brahmic script family.",
      "totalSpeakers": "300 million",
      "languageFamily": "Indo-European, Indo-Aryan",
      "sampleGreeting": "নমস্কার (Nomoshkar)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/0/02/Bn-nomoshkar.ogg"
    },
    {
      "title": "Portuguese",
      "wikiLink": "https://en.wikipedia.org/wiki/Portuguese_language",
      "imageUrl": "images/portuguese.jpg",
      "altText": "Page from 'Os Lusíadas', a Portuguese epic poem",
      "text": "Portuguese is a Romance language originating in the Iberian Peninsula of Europe. It is the official language of Portugal, Brazil, Cape Verde, Angola, Mozambique, Guinea-Bissau and São Tomé and Príncipe. With approximately 250 million total speakers, it is the sixth most spoken language in the world and the most widely spoken language in South America.",
      "totalSpeakers": "250 million",
      "languageFamily": "Indo-European, Romance",
      "sampleGreeting": "Olá! Como vai?",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/8/83/Pt-br-ol%C3%A1.ogg"
    },
    {
      "title": "Russian",
      "wikiLink": "https://en.wikipedia.org/wiki/Russian_language",
      "imageUrl": "images/russian.png",
      "altText": "Example of Russian Cyrillic handwriting",
      "text": "Russian is an East Slavic language native to Russia and Belarus. It is the most geographically widespread language of Eurasia and the most widely spoken of the Slavic languages. Russian uses the Cyrillic script and is the official language of Russia, Belarus, Kazakhstan, and Kyrgyzstan, and is used widely throughout the former Soviet Union.",
      "totalSpeakers": "258 million",
      "languageFamily": "Indo-European, Slavic",
      "sampleGreeting": "Здравствуйте! (Zdravstvuyte)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/6/66/Ru-zdravstvuite.ogg"
    },
    {
      "title": "Japanese",
      "wikiLink": "https://en.wikipedia.org/wiki/Japanese_language",
      "imageUrl": "images/japanese.png",
      "altText": "Example of Japanese writing with kanji, hiragana, and katakana",
      "text": "Japanese is an East Asian language spoken by about 128 million people, primarily in Japan, where it is the official language. It is a member of the Japonic language family, and its written form uses a combination of three scripts: kanji (Chinese characters), and hiragana and katakana (two phonetic scripts). Japanese has a complex system of honorifics and formal speech.",
      "totalSpeakers": "128 million",
      "languageFamily": "Japonic",
      "sampleGreeting": "こんにちは (Konnichiwa)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/8/83/Ja-konnichiwa.ogg"
    },
    {
      "title": "Punjabi",
      "wikiLink": "https://en.wikipedia.org/wiki/Punjabi_language",
      "imageUrl": "images/punjabi.png",
      "altText": "The Gurmukhi alphabet used for Punjabi in India",
      "text": "Punjabi is an Indo-Aryan language with about 125 million native speakers worldwide. It is the most widely spoken language in Pakistan and the 11th most widely spoken in India. In Pakistan, it is written using the Shahmukhi script (a variant of the Perso-Arabic script), while in India it is written in the Gurmukhi script.",
      "totalSpeakers": "125 million",
      "languageFamily": "Indo-European, Indo-Aryan",
      "sampleGreeting": "ਸਤ ਸ੍ਰੀ ਅਕਾਲ (Sat Sri Akal)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/1/19/Pa-Sat_Sri_Akal.ogg"
    },
    {
      "title": "German",
      "wikiLink": "https://en.wikipedia.org/wiki/German_language",
      "imageUrl": "images/german.jpg",
      "altText": "Example of old German script",
      "text": "German is a West Germanic language mainly spoken in Central Europe. It is the most widely spoken and official or co-official language in Germany, Austria, Switzerland, Liechtenstein, and the Italian province of South Tyrol. German is known for its compound words, complex grammar with four noun cases, and three grammatical genders.",
      "totalSpeakers": "132 million",
      "languageFamily": "Indo-European, Germanic",
      "sampleGreeting": "Guten Tag! Wie geht es Ihnen?",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b2/De-Guten_Tag.ogg"
    },
    {
      "title": "Javanese",
      "wikiLink": "https://en.wikipedia.org/wiki/Javanese_language",
      "imageUrl": "images/javanese.png",
      "altText": "Javanese script hanacaraka",
      "text": "Javanese is a language spoken by the Javanese people from the central and eastern parts of the island of Java, Indonesia. It has approximately 82 million native speakers and is the largest of the Austronesian languages in number of speakers. Traditionally written with its own script, called Aksara Jawa, it is now more commonly written with the Latin alphabet.",
      "totalSpeakers": "82 million",
      "languageFamily": "Austronesian, Malayo-Polynesian",
      "sampleGreeting": "Mangga (formal) or Halo (informal)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Jv-Mangga.ogg"
    },
    {
      "title": "Wu Chinese",
      "wikiLink": "https://en.wikipedia.org/wiki/Wu_Chinese",
      "imageUrl": "images/wu chinese.png",
      "altText": "Map showing regions where Wu Chinese is spoken",
      "text": "Wu Chinese is a group of linguistically similar and related Sinitic languages spoken primarily in Shanghai, Zhejiang Province, and the southern parts of Jiangsu Province in China. Wu Chinese is notable among Chinese languages for having preserved the voiced initials from Middle Chinese, which sets it apart from Mandarin and other varieties.",
      "totalSpeakers": "81 million",
      "languageFamily": "Sino-Tibetan, Sinitic",
      "sampleGreeting": "侬好 (Nong hao)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Wuu-n%C3%B3%C5%8Bh%C3%A3%C3%B2%C2%B7.ogg"
    },
    {
      "title": "Telugu",
      "wikiLink": "https://en.wikipedia.org/wiki/Telugu_language",
      "imageUrl": "images/telugu.png",
      "altText": "Telugu script vowels",
      "text": "Telugu is a Dravidian language native to India. It stands alongside Hindi, English and Bengali as one of the few languages with primary official status in more than one Indian state. It is the primary language in the states of Andhra Pradesh, Telangana, and the union territory of Puducherry. Telugu is known for its mellifluous quality and is often called 'Italian of the East'.",
      "totalSpeakers": "81 million",
      "languageFamily": "Dravidian, South-Central",
      "sampleGreeting": "నమస్కారం (Namaskaram)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/4/40/Te-namaskaram.ogg"
    },
    {
      "title": "Vietnamese",
      "wikiLink": "https://en.wikipedia.org/wiki/Vietnamese_language",
      "imageUrl": "images/vietnamese.png",
      "altText": "Example of Vietnamese text using Latin alphabet with diacritics",
      "text": "Vietnamese is an Austroasiatic language originating in Vietnam. It is the official language of Vietnam and a first or second language for many ethnic minorities of Vietnam. Although Vietnamese was historically written using Chinese characters, it now uses a Latin-based alphabet with additional diacritics for tones and certain vowels. Vietnamese is a tonal language with six distinct tones.",
      "totalSpeakers": "85 million",
      "languageFamily": "Austroasiatic, Vietic",
      "sampleGreeting": "Xin chào!",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Vi-xinchao.ogg"
    },
    {
      "title": "Marathi",
      "wikiLink": "https://en.wikipedia.org/wiki/Marathi_language",
      "imageUrl": "images/marathi.png",
      "altText": "Example of Marathi text in Devanagari script",
      "text": "Marathi is an Indo-Aryan language spoken predominantly by Marathi people in the Indian states of Maharashtra and Goa. With approximately 83 million speakers, it is the third most spoken native language in India. Marathi uses the Devanagari script and has a rich literary history dating back to around 900 CE.",
      "totalSpeakers": "83 million",
      "languageFamily": "Indo-European, Indo-Aryan",
      "sampleGreeting": "नमस्कार (Namaskar)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/5/55/Mr-Namaskar.ogg"
    },
    {
      "title": "Tamil",
      "wikiLink": "https://en.wikipedia.org/wiki/Tamil_language",
      "imageUrl": "images/tamil.png",
      "altText": "Tamil script characters",
      "text": "Tamil is a Dravidian language natively spoken by the Tamil people of South Asia. Tamil is an official language in Sri Lanka, Singapore, and India, specifically in the state of Tamil Nadu and the union territory of Puducherry. It has significant minorities of speakers in Malaysia, Mauritius, and South Africa. Tamil is one of the world's longest-surviving classical languages.",
      "totalSpeakers": "75 million",
      "languageFamily": "Dravidian, Southern",
      "sampleGreeting": "வணக்கம் (Vanakkam)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Ta-vanakkam.ogg"
    },
    {
      "title": "French",
      "wikiLink": "https://en.wikipedia.org/wiki/French_language",
      "imageUrl": "images/french.jpg",
      "altText": "Page from Jean Anouilh's 'Antigone' in French",
      "text": "French is a Romance language descended from Latin. It is the official language in 29 countries across multiple continents, and is a working language in numerous international organizations. French was historically the international language of diplomacy and remains influential in the arts, cuisine, and fashion. It's known for its elegant pronunciation and is the second most studied foreign language in the world after English.",
      "totalSpeakers": "280 million",
      "languageFamily": "Indo-European, Romance",
      "sampleGreeting": "Bonjour! Comment allez-vous?",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Fr-Bonjour.ogg"
    },
    {
      "title": "Korean",
      "wikiLink": "https://en.wikipedia.org/wiki/Korean_language",
      "imageUrl": "images/korean.png",
      "altText": "Hunmin Jeongeum manuscript - first Korean alphabet text",
      "text": "Korean is an East Asian language spoken by about 77 million people, mainly Korean, as of 2020. It is the official and national language of both North and South Korea, with different standardized official forms used in each country. Korean is written in its own alphabet called Hangul, which was created in the 15th century. Linguistically, Korean is often classified as a language isolate.",
      "totalSpeakers": "77 million",
      "languageFamily": "Koreanic (language isolate)",
      "sampleGreeting": "안녕하세요 (Annyeong haseyo)",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/4/43/Korean_Annyeonghaseyo.ogg"
    },
    {
      "title": "Turkish",
      "wikiLink": "https://en.wikipedia.org/wiki/Turkish_language",
      "imageUrl": "images/turkish.jpg",
      "altText": "Page from Atatürk's speech 'Nutuk' in Turkish",
      "text": "Turkish is a Turkic language spoken as a first language by around 80 million people worldwide. It is the official language of Turkey and Northern Cyprus, and has official status in Cyprus. Turkish is notable for its vowel harmony and agglutinative structure. Since a language reform in 1928, it has been written in a Latin alphabet with some additional letters.",
      "totalSpeakers": "88 million",
      "languageFamily": "Turkic, Oghuz",
      "sampleGreeting": "Merhaba! Nasılsınız?",
      "pronunciationUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Merhaba_-_Turkish.ogg"
    }
  ]